author: Rhys # 作者
description: Rhys's blog
keyword: hexo-theme, vuejs
favicon: 

excerpt_link: Read more

menu:
 Home: /
 Tags: /tags/
 Archives: /archives/
 Projects: /project/
 About: /about/

# highlight
highlight:
  tomorrow

# catalog
catalog: true

# donate
donate: false

# qrcode
qrcode: false

# comment
# you can set gitment, uyan or disqus

comment: gitment

# gitment config
gitment_owner: rhyspang
gitment_repo: rhyspang.github.io
gitment_oauth_id: 0f87e490e00ee3fd87ef
gitment_oauth_secret: 6b410b7c4e04835b8df258724459b659d2ba3fc3

# uyan config
# if you want to use uyan as your blog comment, plz remove/comment out gitment config
baidu_id: 

# disqus config
disqus_shortname: 

about: 
  banner: http://file.muyutech.com/about.jpg
  avatar: https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1546172811820&di=225445c158bb8ef5ba7002f0212897bb&imgtype=0&src=http%3A%2F%2Fimg.zcool.cn%2Fcommunity%2F01b5745a43665ea801219741444cb2.jpg%401280w_1l_2o_100sh.jpg
  description: "keep calm and carry on."
  weibo_username: rhyspang
  twitter_username: rhyspang
  github_username: rhyspang
  zhihu_username: rhyspang
  douban_username: rhyspang
  linkedin_username:

# MathJax Support
mathjax:
  enable: true
  per_page: false
  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML
